---

- name: setup devbox
  hosts: 127.0.0.1
  connection: local
  become: yes
  gather_facts: no

  vars_prompt:
    - name: "git_email"
      prompt: "What email should be used for Git commits?"
      private: no

    - name: "user_password"
      prompt: "What should the user password be?"
      private: yes

  tasks:

  - name: update apt
    apt: update_cache=yes
  - name: upgrade apt
    apt: upgrade=yes

  - name: install git
    apt:
      name: git

  - name: install curl
    apt:
      name: curl

  - name: install vim
    apt:
      name: vim

  - name: install tmux
    apt:
      name: tmux

  - name: install xclip
    apt:
      name: xclip

  - name: install zsh
    apt:
      name: zsh

  - name: install kubectl
    block:
      - name: add google apt key
        ansible.builtin.apt_key:
          url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          state: present
      - name: add kubernetes apt repo
        ansible.builtin.apt_repository:
          repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      - name: update apt
        apt: update_cache=yes
      - name: install kubectl package
        apt:
          name: kubectl

  - name: install github cli
    block:
      - name: add github apt key
        ansible.builtin.apt_key:
          keyserver: keyserver.ubuntu.com
          id: C99B11DEB97541F0
          state: present
      - name: add github apt repo
        ansible.builtin.apt_repository:
          repo: deb https://cli.github.com/packages bionic main
      - name: update apt
        apt: update_cache=yes
      - name: install github cli apt package
        apt:
          name: gh

  - name: set git email
    command: git config --global user.email {{ git_email }}

  - name: create my user
    register: user_output
    user:
      name: karl
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
      password: "{{ user_password | password_hash('sha512') }}"
      groups: "sudo"

  - name: continue as karl
    become_user: karl
    block:

      - name: checkout dotfiles repo
        git:
          repo: https://github.com/agentreno/dotfiles
          dest: /home/karl/dotfiles
          accept_hostkey: yes

      - name: symlink vimrc from dotfiles to home folder
        file:
          path: /home/karl/.vimrc
          src: /home/karl/dotfiles/vimfiles/vimrc
          state: link
          force: yes

      - name: symlink vimrc from dotfiles to home folder
        file:
          path: /home/karl/.vim
          src: /home/karl/dotfiles/vimfiles
          state: link
          force: yes

      - name: symlink tmux config from dotfiles to home folder
        file:
          path: /home/karl/.tmux.conf
          src: /home/karl/dotfiles/.tmux.conf
          state: link
          force: yes

      - name: symlink git config
        file:
          path: /home/karl/.gitconfig
          src: /home/karl/dotfiles/.gitconfig
          state: link
          force: yes

      - name: setup build environment for python
        become_user: root
        apt:
          name: "{{ packages }}"
        vars:
          packages:
          - make
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncurses5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev

      - name: install pyenv
        shell: curl https://pyenv.run | bash
        ignore_errors: yes

      - name: setup pyenv
        script: /home/karl/dotfiles/setup_pyenv.sh

      - name: make flake8 config directory
        file:
          path: /home/karl/.config
          state: directory

      - name: symlink flake8 config
        file:
          path: /home/karl/.config/flake8
          src: /home/karl/dotfiles/.flake8
          state: link
          force: yes

      - name: symlink zsh config
        file:
          path: /home/karl/.zshrc
          src: /home/karl/dotfiles/.zshrc
          state: link
          force: yes

      - name: run zsh install
        script: /home/karl/dotfiles/install-oh-my-zsh.sh
        ignore_errors: yes

      - name: set zsh as default shell
        become_user: root
        shell: chsh karl -s /usr/bin/zsh

      - name: switch to zsh
        shell: zsh

      - name: reminders
        shell: echo "Remember to register SSH key on Github"
