name: test-dotfiles
on:
  push:
    tags: v*
jobs:
  run-dotfiles:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: ./bootstrap-ansible.sh test
      - run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - run: inspec exec tests/inspec.rb
        env:
          CHEF_LICENSE: accept-no-persist
